enforce_in_prod = true

[[rules]]
env = "prod"
capability_prefix = "rag."
allowed_service_names = ["relayorb-rag-prod"]
allowed_service_accounts = [
  "304025149431-compute@developer.gserviceaccount.com",
]

[[rules]]
env = "prod"
capability_prefix = "sql."
allowed_service_names = ["relayorb-sql-prod"]

[[rules]]
env = "prod"
capability_prefix = "doc."
allowed_service_names = ["relayorb-doc-prod"]
